### ISSUE TITLE
Fix browserify usage

### ISSUE THREAD

**Issue by jamiebuilds** [thoughtram/es6-browserify-boilerplate#3]
A couple things:
- It is considered a bad practice to use gulp-browserify over the normal browserify module.
- Should be using the es6ify transform instead of separate gulp transforms.
- Browserify should have a single entry point.
- Should be using watchify instead of gulp watch if you want fast builds.

Resources:
- https://github.com/thlorenz/es6ify
- https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md

**Comment by cburgdorf** [comment]
Thank you for the great feedback. I'll fix that asap.
Am 24.11.2014 06:15 schrieb "James Kyle" notifications@github.com:

**Comment by 0x-r4bbit** [comment]
hey @thejameskyle this is very helpful!

I already started moving from gulp-browserify to 6to5-browserify. However, currently we're keeping the transpiled es5 code in `compiled/src` and as far as I understand, there's no way to get the "in-between" state of the file stream that results of `browserify.transform(6to5Browserify)`.

Do you know, if that's possible somehow?

**Comment by 0x-r4bbit** [comment]
Doh'! Just realised that this is not the `6to5` repo. Nvm then.

**Comment by jamiebuilds** [comment]
What's your reasoning for wanting the compiled es5 code separate from the browserify bundle?

**Comment by cburgdorf** [comment]
Nothing specific. This is a fork of a different boilerplate and I just left
many parts the way they were.
Am 24.11.2014 17:26 schrieb "James Kyle" notifications@github.com:

**Comment by jamiebuilds** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
